export const CITIES = [
  { id: "msk", label: "Москва" },
  { id: "spb", label: "Санкт-Петербург" },
  { id: "ekb", label: "Екатеринбург" },
  { id: "kzn", label: "Казань" },
  { id: "nn", label: "Нижний Новгород" },
  { id: "smr", label: "Самара" },
  { id: "nsk", label: "Новосибирск" },
  { id: "che", label: "Челябинск" },
  { id: "krr", label: "Краснодар" },
  { id: "rnd", label: "Ростов-на-Дону" },
  { id: "ufa", label: "Уфа" },
  { id: "kja", label: "Красноярск" },
  { id: "prm", label: "Пермь" },
  { id: "vog", label: "Волгоград" },
  { id: "vrn", label: "Воронеж" },
  { id: "oms", label: "Омск" },
  { id: "srg", label: "Сургут" },
  { id: "tmn", label: "Тюмень" },
  { id: "saratov", label: "Саратов" },
  { id: "tol", label: "Тольятти" },
  { id: "izhesh", label: "Ижевск" },
  { id: "uln", label: "Ульяновск" },
  { id: "brn", label: "Барнаул" },
  { id: "irk", label: "Иркутск" },
  { id: "khv", label: "Хабаровск" },
  { id: "vvo", label: "Владивосток" },
  { id: "yar", label: "Ярославль" },
  { id: "orenburg", label: "Оренбург" },
  { id: "nab", label: "Набережные Челны" },
  { id: "ryazan", label: "Рязань" },
];

export const AUCTION_TYPE = [
  { value: "Request", label: "Запрос цен" },
  { value: "Up", label: "На повышение" },
  { value: "Down", label: "На понижение" },
  { value: "FixPrice", label: "Фикс. цена" },
];

export const AUCTION_STATUS = [
  { value: "planning", label: "Планирование" },
  { value: "auction", label: "Аукцион" },
  { value: "determinateWinner", label: "Определение победителя" },
  { value: "waitDeal", label: "Ожидание сделки" },
  { value: "inProgress", label: "В работе" },
  { value: "finished", label: "Завершен" },
  { value: "stopped", label: "Остановлен" },
  { value: "canceled", label: "Отменен" },
];
