/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './__root'
import { Route as pagesIndexRouteImport } from './(pages)/index'

const pagesAuctionIdLazyRouteImport = createFileRoute('/(pages)/auction/$id')()
const pagesBidsIdLazyRouteImport = createFileRoute('/(pages)/bids/$id')()

const pagesIndexRoute = pagesIndexRouteImport.update({
  id: '/(pages)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAuctionIdLazyRoute = pagesAuctionIdLazyRouteImport
  .update({
    id: '/(pages)/auction/$id',
    path: '/auction/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./(pages)/auction/$id.lazy').then((d) => d.Route))
const pagesBidsIdLazyRoute = pagesBidsIdLazyRouteImport
  .update({
    id: '/(pages)/bids/$id',
    path: '/bids/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./(pages)/bids/$id.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof pagesIndexRoute
  '/auction/$id': typeof pagesAuctionIdLazyRoute
  '/bids/$id': typeof pagesBidsIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof pagesIndexRoute
  '/auction/$id': typeof pagesAuctionIdLazyRoute
  '/bids/$id': typeof pagesBidsIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(pages)/': typeof pagesIndexRoute
  '/(pages)/auction/$id': typeof pagesAuctionIdLazyRoute
  '/(pages)/bids/$id': typeof pagesBidsIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auction/$id' | '/bids/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auction/$id' | '/bids/$id'
  id: '__root__' | '/(pages)/' | '/(pages)/auction/$id' | '/(pages)/bids/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  pagesIndexRoute: typeof pagesIndexRoute
  pagesAuctionIdLazyRoute: typeof pagesAuctionIdLazyRoute
  pagesBidsIdLazyRoute: typeof pagesBidsIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)/': {
      id: '/(pages)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/auction/$id': {
      id: '/(pages)/auction/$id'
      path: '/auction/$id'
      fullPath: '/auction/$id'
      preLoaderRoute: typeof pagesAuctionIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/bids/$id': {
      id: '/(pages)/bids/$id'
      path: '/bids/$id'
      fullPath: '/bids/$id'
      preLoaderRoute: typeof pagesBidsIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  pagesIndexRoute: pagesIndexRoute,
  pagesAuctionIdLazyRoute: pagesAuctionIdLazyRoute,
  pagesBidsIdLazyRoute: pagesBidsIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
